---
title: "IFLS5_cleaning"
author: "Chenoa Schatzki-McClain"
date: "March 31, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r clear environment}

rm(list=ls())

```

```{r load libraries}
library(foreign)
library(dplyr)
```

```{r load and subset COV section}

#load B3A_COV IFLS5
B3A_COV <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS5/b3a_cov.dta")

#add wave variable and filter to selected vars
B3A_COV <- B3A_COV %>%
                select(pid14, hhid14, hhid14_9, pidlink, sex, rspndnt, marstat, panel, age) %>%
                mutate(wave = 5)
```

```{r TK section}

#load B3A_TK1 IFLS5
B3A_TK1 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS5/b3a_tk1.dta")
#subset
B3A_TK1 <- B3A_TK1 %>%
                select(pid14, hhid14, hhid14_9, pidlink, tk01, tk01a, tk03, tk04, tk05, tk06a, tk07)

#load B3A_TK2 IFLS5
B3A_TK2 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS5/b3a_tk2.dta")
#subset
B3A_TK2 <- B3A_TK2 %>%
                select(pid14, hhid14, hhid14_9, pidlink, tk22a, tk23a, tk23a2y, tk24a, tk25a1x, tk24a5, tk25a1, tk25a2, tk26a1, tk26a3)

#load B3A_TK4 IFLS5
B3A_TK4 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS5/b3a_tk4.dta")
#subset
B3A_TK4 <- B3A_TK4 %>%
                 select(pid14, hhid14, hhid14_9, pidlink, tk46a, tk46b, tk46c, tk46dm, tk46dy, tk46m)

#merge TK files

#TK 1 and 2 include all of the same respondents
TK_merge <- inner_join(B3A_TK1, B3A_TK2, by = c("hhid14", "hhid14_9", "pid14"))

TK_merge <- left_join(TK_merge, B3A_TK4, by = c("hhid14", "hhid14_9", "pid14"))

#no respondents answered tk05 and tk06
table(TK_merge$tk05)
table(TK_merge$tk05)

#LOOK AT THIS
TK4_missing <- TK_merge[!(TK_merge$pidlink %in% B3A_TK4$pidlink),] 

```

```{r interview time}

#add interview time
B3A_TIME <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS5/b3a_time.dta")

#includes multiple entries with times of all interviews. take time from first interview
B3A_TIME <- B3A_TIME %>%
                filter(time_occ == 1)

B3A_TIME <- B3A_TIME %>%
                select(ivwmth, ivwyr, hhid14, pid14)

```

```{r B3A_DL2}

#load >> DL2 ids don't match well when merged later. not sure why
#B3A_DL2 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS5/b3a_dl2.dta")

#subset
#B3A_DL2 <- B3A_DL2 %>%
               # select(pid14, hhid14, pidlink, dl2type)


#load
B3A_DL1 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS5/b3a_dl1.dta")

#subset
B3A_DL1 <- B3A_DL1 %>%
                select(pid14, hhid14, pidlink, dl06x, dl06, dl04)


```

```{r B3A_BR1}

#load
B3A_BR1 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS5/b3a_br1.dta")

#subset
B3A_BR1<- B3A_BR1 %>%
                select(pid14, hhid14, pidlink, br03, br04)

```

```{r BK_AR1}

#load
BK_AR1 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS5/bk_ar1.dta")

#subset
BK_AR1 <- BK_AR1 %>%
                select(pid14, hhid14, hhid14_9, pidlink, ar02, ar13, ar14, ar09, ar10, ar11, ar02b, ar15a)

BK_AR1_spouse_link <- BK_AR1 %>%
                select(pid14, hhid14, hhid14_9, pidlink, ar13, ar14)

```


```{r  merge}

#first merge cov with tk
merged <- full_join(B3A_COV, TK_merge, by = c("hhid14", "pid14", "hhid14_9"))

missing1 <- merged[!(merged$pidlink %in% TK_merge$pidlink),] 

#merge BR1 > all matched
merged <- full_join(merged, B3A_BR1, by = c("hhid14", "pid14"))

# merge DL1 > all matched
merged <- full_join(merged, B3A_DL1, by = c("hhid14", "pid14"))

#merge B3A_TIME >>> things aren't matching, introducing repeats
merged <- full_join(merged, B3A_TIME, by = c("hhid14", "pid14"))

#merge DL2 >> issue with matches
#merged <- full_join(merged, B3A_DL2, by = c("hhid14", "pid14"))

#spouse info
merged <- left_join(merged, BK_AR1_spouse_link, by = c("hhid14", "pid14"))


#remove observation w/ pidlink == NA
#merged <- merged %>%
 #             filter(!(is.na(merged$pidlink)))

```

```{r}

# filter to just include wives
#only two levels for sex, female == 2
#many levels for marrital status, married = 2
wives <- merged %>%
            filter(sex == "3:Female", as.numeric(marstat) == 2)

```

```{r}

#subset data on husbands
husbands <- merged %>%
              filter(as.numeric(sex) == 1, as.numeric(marstat) == 2) %>%
              select(hhid14, pid14, age, tk22a, tk24a, tk24a5, tk25a1x, tk25a1, tk25a2, tk26a1, tk26a3, tk46a, tk46b, tk46c, tk46dm, tk46dy, tk46m, tk01, tk01a, tk03, tk04, tk05, tk06a, tk07, dl04, dl06, dl06x, ar14)

#rename husband vars
names(husbands)[2:length(husbands)] <- paste0(names(husbands)[2:length(husbands)], "_H") 

```

```{r add husband data to wives}
wives <- wives %>%
            filter(ar14 != 51)


#merge husband data >> match HH, match husband's PID w/ AR14 and vice versa
#will eliminate observations where husband is not located ******************

wives <- inner_join(wives, husbands, by = c("hhid14"= "hhid14", "ar14" = "pid14_H", "pid14" = "ar14_H"))


wives_repeated_H <- wives %>%
                    group_by(hhid14_9.x, ar14) %>%
                    summarise(repeats = n()) %>%
                    filter(repeats >1)



```

```{r household info}

#dependents, working dependents

household_mother_summary <- BK_AR1 %>%
                        filter(!(ar11 %in% c(51, 52, 98))) %>%
                        group_by(hhid14, ar11) %>%
                        summarize(dependents = sum(ar09 < 15), dependents_young = sum(ar09 < 6), dependents_old = sum(ar09> 5 & ar09 < 15), working_dependents = sum(ar09 < 15 & as.numeric(ar15a) == 1))


household_member_summary <- BK_AR1 %>%
                            group_by(hhid14) %>%
                            mutate(working = ifelse(is.na(ar15a), 0, ifelse(as.numeric(ar15a) == 1, 1, 0))) %>%
                            summarize(HHM =  n() , working_HHM =  sum(working == 1))


#add dependents and working dependents to wives' data
wives <- wives %>%
            left_join(household_mother_summary, by = c("hhid14" = "hhid14", "pid14" = "ar11")) %>%
            mutate (dependents = ifelse(is.na(dependents), 0, dependents), working_dependents = ifelse(is.na(working_dependents), 0, working_dependents), dependents_young = ifelse(is.na(dependents_young), 0, dependents_young), dependents_old = ifelse(is.na(dependents_old), 0, dependents_old))

#add HHM data to wives data
wives <- wives %>%
            left_join(household_member_summary, by = c("hhid14" = "hhid14"))

#add other HHM and other working
wives <- wives %>%
          mutate(other_HHM = HHM - dependents, other_working = working_HHM - working_dependents)






#province and urban/rural

BK_SC1 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS5/bk_sc1.dta")

BK_SC1 <- BK_SC1 %>%
              select(hhid14, sc05, sc01_14_14) 

#add hh geo data to wives data
wives <- wives %>%
            left_join(BK_SC1, by = "hhid14")




```

```{r recode to match IFLS4}

wives$tk01 <- ifelse(as.numeric(wives$tk01) == 7, NA, as.character(wives$tk01))
wives$tk01_H <- ifelse(wives$tk01_H == "95:Other", NA, as.character(wives$tk01_H))

#recode tk01a, tk03, tk24
wives$tk01a <- ifelse(wives$tk01a ==  "8:Don't Know", NA, as.character(wives$tk01a))
wives$tk03 <- ifelse(wives$tk03 == "8:Don't Know", NA, as.character(wives$tk03))
wives$tk24a <- ifelse(wives$tk24a == "8:Don't Know", NA, as.character(wives$tk24a))

#recode tk46m_H
wives$tk46m_H <- ifelse(wives$tk46m_H == "95:Other", NA, as.character(wives$tk46m_H))

#recode tk46dy_H
wives$tk46dy_H <- ifelse(wives$tk46dy_H %in%c(9998, 9999), NA, wives$tk46dy_H)

#recode dl04 and dl04_H
wives$dl04 <- ifelse(wives$dl04 == "8:MISSING" | wives$dl04 == "9:Don't Know", NA, as.character(wives$dl04))
wives$dl04_H <- ifelse(wives$dl04_H == "8:MISSING" | wives$dl04_H == "9:Don't Know", NA, as.character(wives$dl04_H))

#recode tk24a
wives$tk24a <- ifelse(wives$tk24a == "9:Missing", NA, as.character(wives$tk24a))

#recode tk24a5
wives$tk24a5 <- ifelse(wives$tk24a5 %in% c("8:Don't Know", "9:Missing"), NA, wives$tk24a5)
wives$tk24a5_H <- ifelse(wives$tk24a5_H %in% c("8:Don't Know", "9:Missing"), NA, wives$tk24a5_H)

#recode tk46dm_H
wives$tk46dm_H <- ifelse(wives$tk46dm_H == "98:Don't Know", NA, wives$tk46dm_H)

#convert back to factors
factor_vars <- c("tk01", "tk01_H", "tk01a", "tk03", "tk24a", "tk46m_H", "dl04", "dl04_H", "tk24a")

for (i in 1:length(factor_vars)){
  wives[,factor_vars[i]] <- as.factor(wives[,factor_vars[i]])
}




#remove weird case with inconsistent marrital status
wives <- wives %>%
            filter(paste0(marstat) == paste0(ar13))

```

```{r write data to file}

write.csv(wives, file = "C:/Users/cheno/Desktop/IFLS_all/DATA/R datasets/IFLS5.csv")

```
