---
title: "IFLS_4_5 IFLS_4_5ing"
author: "Chenoa Schatzki-McClain"
date: "April 7, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(lubridate)
library(dplyr)

```

```{r clear environment}

rm(list=ls())

```

```{r}

#load data
IFLS_4_5 <- read.csv("C:/Users/cheno/Desktop/IFLS_all/DATA/R datasets/IFLS_4_5.csv")

#remove unneeded variables
vars <- c("marstat", "sex", "pidlink.x", "pidlink.x.x", "pidlink.x.x.x", "pidlink.y", "pidlink.y.y", "pidlink.y.y.y", "X", "X.1", "br03", "br04")

for (i in 1:length(vars)){
  IFLS_4_5[, vars[i]] <- NULL 
}

```

```{r}

#remove salary top-coding

IFLS_4_5$tk25a1 <- ifelse(IFLS_4_5$tk25a1 == 999999997, NA, IFLS_4_5$tk25a1)
IFLS_4_5$tk25a1_H <- ifelse(IFLS_4_5$tk25a1_H == 999999997, NA, IFLS_4_5$tk25a1_H)


#remove num job losses top coding >> remove 39
IFLS_4_5$tk46c <- ifelse(IFLS_4_5$tk46c == 99 | IFLS_4_5$tk46c == 98, NA, IFLS_4_5$tk46c)
IFLS_4_5$tk46c_H <- ifelse(IFLS_4_5$tk46c_H == 99  | IFLS_4_5$tk46c_H == 98, NA, IFLS_4_5$tk46c_H)

```



```{r emp vars W}

#add employment status variable

IFLS_4_5$employed <- c()

for (i in 1:nrow(IFLS_4_5)){
  
  IFLS_4_5[i, "employed"] <- ifelse(1 %in% as.numeric(IFLS_4_5[i,c("tk01", "tk01a", "tk03", "tk04")]), "1:Employed", "2:Unemployed")
  
}

IFLS_4_5$employed <- as.factor(IFLS_4_5$employed)

#add ever worked var based on employed and tk05

IFLS_4_5$ever_emp <- ifelse(IFLS_4_5$employed == "1:Employed"| IFLS_4_5$tk06a_H == 1, 1, IFLS_4_5$tk05)

IFLS_4_5$ever_emp <- as.factor(IFLS_4_5$ever_emp)


levels(IFLS_4_5$ever_emp) <- c("1:Yes", "2:No")

```

```{r emp vars H}

#add employment status variable

IFLS_4_5$employed_H <- c()

for (i in 1:nrow(IFLS_4_5)){
  
  IFLS_4_5[i, "employed_H"] <- ifelse(1 %in% as.numeric(IFLS_4_5[i,c("tk01_H", "tk01a_H", "tk03_H", "tk04_H")]), "1:Employed", "2:Unemployed")
  
}

IFLS_4_5$employed_H <- as.factor(IFLS_4_5$employed_H)

#add ever worked var based on employed, tk05, and tk06a

IFLS_4_5$ever_emp_H <- ifelse(IFLS_4_5$employed_H == "1:Employed" | IFLS_4_5$tk06a_H == 1, 1, IFLS_4_5$tk05_H)

IFLS_4_5$ever_emp_H <- as.factor(IFLS_4_5$ever_emp_H)


levels(IFLS_4_5$ever_emp_H) <- c("1:Yes", "2:No")


```

```{r}

#fix age top-coding

IFLS_4_5$age_H <- ifelse(IFLS_4_5$age_H == 998, NA, IFLS_4_5$age_H)

```

```{r}

#job loss in last 5 years

IFLS_4_5$job_loss <- ifelse(IFLS_4_5$ever_emp == "3:No" | IFLS_4_5$tk46a == "3:No", 2, IFLS_4_5$tk46b)

IFLS_4_5$job_loss_H <- ifelse(IFLS_4_5$ever_emp_H == "3:No" | IFLS_4_5$tk46a_H == "3:No", 2, IFLS_4_5$tk46b_H)

IFLS_4_5$job_loss <- as.factor(IFLS_4_5$job_loss)
IFLS_4_5$job_loss_H <- as.factor(IFLS_4_5$job_loss_H)

levels(IFLS_4_5$job_loss) <- levels(IFLS_4_5$ever_emp)
levels(IFLS_4_5$job_loss_H) <- levels(IFLS_4_5$ever_emp)


```

```{r hours}

#wage info available??

#lots of missing wage info, even for workers in private sector
length(IFLS_4_5[which((is.na(IFLS_4_5$tk25a1_H)) & as.numeric(IFLS_4_5$employed_H) == 1),1])
length(IFLS_4_5[which((is.na(IFLS_4_5$tk25a1_H)) & as.numeric(IFLS_4_5$tk24a) == 5),1])

#job type available >>> job type is available for almost all workers >> could serve as a proxy for wage
length(IFLS_4_5[which((is.na(IFLS_4_5$tk24a)) & as.numeric(IFLS_4_5$employed) == 1),1])
length(IFLS_4_5[which((is.na(IFLS_4_5$tk24a_H)) & as.numeric(IFLS_4_5$employed_H) == 1),1])




```

```{r}

#compute time between job loss and interview date

#construct interview date and job loss date
IFLS_4_5 <- IFLS_4_5 %>%
            mutate(interview_d = mdy(paste0(ivwmth, "/1/", ivwyr)), 
                   jl_d_H = ifelse((is.na(tk46dm_H)), NA, (paste0(tk46dm_H, "/1/", tk46dy_H))))

IFLS_4_5$jl_d_H <- mdy(IFLS_4_5$jl_d_H)

#variable for time between survey and job loss
IFLS_4_5$jl_year <- ceiling(ifelse(is.na(IFLS_4_5$jl_d_H), 0, interval(IFLS_4_5$jl_d_H, IFLS_4_5$interview_d)/dyears()))

#month missing in many instances, compute based on year
#IFLS_4_5$jl_year <- ifelse(is.na(IFLS_4_5$tk46dy_H), 0, IFLS_4_5$ivwyr - IFLS_4_5$tk46dy_H + 1)

#recode for job losses beyond 5 years, likely a recording error, address in data section
IFLS_4_5$jl_year <- ifelse(IFLS_4_5$jl_year >5, 0, IFLS_4_5$jl_year)

#convert to factor
IFLS_4_5$jl_year <- as.factor(IFLS_4_5$jl_year)

```

```{r}

#remove unneeded variables

#remove unneeded variables
vars2 <- c("tk01a", "tk03", "tk04", "tk05", "tk06a", "tk07", "tk25a1x", "tk46a", "tk46b", "dl06x", "ar13", "tk25a1x_H", "tk46a_H", "tk46b_H", "dl06x_H", "dl04_H")

for (i in 1:length(vars)){
  IFLS_4_5[, vars[i]] <- NULL 
}

#wave should be factor
IFLS_4_5$year <- as.factor(IFLS_4_5$wave)

#remove hours top coding
IFLS_4_5$tk22a <- ifelse(IFLS_4_5$tk22a > 120, NA, IFLS_4_5$tk22a)
IFLS_4_5$tk22a_H <- ifelse(IFLS_4_5$tk22a_H > 120, NA, IFLS_4_5$tk22a_H)

```

```{r additional IFLS_4_5ing}

IFLS_4_5$jl_restricted <- ifelse(IFLS_4_5$jl_year %in% 1:2, 1, 0)

IFLS_4_5$employed <- ifelse(as.numeric(IFLS_4_5$employed) == 1, 1, 0)
IFLS_4_5$employed_H <- ifelse(as.numeric(IFLS_4_5$employed_H) == 1, 1, 0)
IFLS_4_5$jl <- ifelse(IFLS_4_5$tk46b_H == "1:Yes" & !(is.na(IFLS_4_5$tk46b_H)), "1", "0")
IFLS_4_5$age_sq <- (IFLS_4_5$age)^2
IFLS_4_5$age_sq_H <- (IFLS_4_5$age_H)^2
IFLS_4_5$jl_year <- as.factor(IFLS_4_5$jl_year)
IFLS_4_5$sc_code <- as.factor(IFLS_4_5$sc_code)
IFLS_4_5$wave <- as.factor(IFLS_4_5$wave)

#wage prof
IFLS_4_5$wage_prof <- ifelse(IFLS_4_5$employed == 0, NA, ifelse(!(is.na(IFLS_4_5$tk25a1)), IFLS_4_5$tk25a1, ifelse(!(is.na(IFLS_4_5$tk26a1)), IFLS_4_5$tk26a1, NA)))

#adjust for inflation CPI 82.668 (2007), 90.75 (2008), 86.709 (2007/2008 average), 124.389 (2014)
IFLS_4_5$wage_prof <- ifelse(!is.na(IFLS_4_5$wage_prof) & IFLS_4_5$wave == 4, IFLS_4_5$wage_prof / 86.709 * 124.389, IFLS_4_5$wage_prof)

IFLS_4_5$wage_prof_H <- ifelse(IFLS_4_5$employed_H == 0, NA, ifelse(!(is.na(IFLS_4_5$tk25a1_H)), IFLS_4_5$tk25a1_H, ifelse(!(is.na(IFLS_4_5$tk26a1_H)), IFLS_4_5$tk26a1_H, NA)))

#adjust for inflation
IFLS_4_5$wage_prof_H <- ifelse(!is.na(IFLS_4_5$wage_prof_H) & IFLS_4_5$wave == 4, IFLS_4_5$wage_prof_H / 86.709 * 124.389, IFLS_4_5$wage_prof_H)

#remove wage outlier >>> optimize this value later on
#IFLS_4_5 <- IFLS_4_5 %>%
#              filter(!(!(is.na(wage_prof)) & wage_prof > 10000000))

#remove workers with no hours (none removed)
IFLS_4_5 <- IFLS_4_5 %>%
              filter(!(!(is.na(IFLS_4_5$tk22a)) & IFLS_4_5$tk22a == 0))

#remove workers with no wage << not an issue (none removed)
IFLS_4_5 <- IFLS_4_5 %>%
              filter(!(!(is.na(wage_prof)) & wage_prof == 0))

#remove observations for which the wife or husband are younger than 18
IFLS_4_5 <- IFLS_4_5 %>%
              filter(age >= 18, age_H >= 18, age<80, age_H <80)

#remove observations for students
IFLS_4_5 <- IFLS_4_5 %>%
              filter(!(!(is.na(dl07a)) & as.numeric(dl07a) == 1) &  !(!(is.na(dl07a_H)) & as.numeric(dl07a_H) == 1))

#limit job loss to firing/displacement
IFLS_4_5$jl_2 <- ifelse(IFLS_4_5$jl == "1" & as.numeric(IFLS_4_5$tk46m_H) %in% c(1, 2, 5), 1, 0)

#limit jl_year based on firings
IFLS_4_5$jl_year_fired <- ifelse(IFLS_4_5$jl_year != "0" & !(as.numeric(IFLS_4_5$tk46m_H) %in% c(1, 2, 5)), 0, as.numeric(IFLS_4_5$jl_year)-1)
IFLS_4_5$jl_year_fired <- as.factor(IFLS_4_5$jl_year_fired)

#eliminate unpaid family workers from employed (employed2)

IFLS_4_5$employed2 <- ifelse(IFLS_4_5$employed == 1 & as.numeric(IFLS_4_5$tk24a) == 6, 0, IFLS_4_5$employed)
IFLS_4_5$employed2_H <- ifelse(IFLS_4_5$employed_H == 1 & as.numeric(IFLS_4_5$tk24a_H) == 6, 0, IFLS_4_5$employed_H)

IFLS_4_5$pidlink <- as.factor(IFLS_4_5$pidlink)




```

```{r create job categories}

#new job cat
cats <- c("2:self-employed", "2:self-employed", "3:informal business owner", "4:government", "5:private", "1:unemployed", "6:casual", "6:casual")

IFLS_4_5$job_cat_H <- c()

for(i in 1:nrow(IFLS_4_5)){
    if(IFLS_4_5$employed_H[i] == 0){
          IFLS_4_5$job_cat_H[i] <- "1:unemployed"
    }
    else {
          IFLS_4_5$job_cat_H[i] <- cats[as.numeric(IFLS_4_5$tk24a_H[i])]
    }
}

IFLS_4_5$job_cat <- c()

for(i in 1:nrow(IFLS_4_5)){
    if(IFLS_4_5$employed[i] == 0){
          IFLS_4_5$job_cat[i] <- "1:unemployed"
    }
    else {
          IFLS_4_5$job_cat[i] <- cats[as.numeric(IFLS_4_5$tk24a[i])]
    }
}

IFLS_4_5$job_cat <- as.factor(IFLS_4_5$job_cat)
IFLS_4_5$job_cat_H <- as.factor(IFLS_4_5$job_cat_H)

#remove observations where individual is unemployed, but has wage and hours
#IFLS_4_5_test <- IFLS_4_5 %>%
#            filter((!(is.na(wage_prof_H)) & wage_prof_H != 0 & as.numeric(job_cat_H) == 1))




```

```{r}

write.csv(IFLS_4_5, file = "C:/Users/cheno/Desktop/IFLS_all/DATA/R datasets/IFLS_4_5_clean.csv")

```