---
title: '"Convert Numeric Vectors to Coded Factors"'
author: "Chenoa Schatzki-McClain"
date: "April 4, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r clear environment}

rm(list=ls())

```

```{r load libraries}
library(stringr)
library(dplyr)
```

```{r load files}

# Load IFLS4 << numeric vectors
IFLS4 <- read.csv("C:/Users/cheno/Desktop/IFLS_all/DATA/R datasets/IFLS4.csv")

# Load IFLS5 << labeled factors
IFLS5 <- read.csv("C:/Users/cheno/Desktop/IFLS_all/DATA/R datasets/IFLS5.csv")

#relabel "respndnt" as "rspndnt" in IFLS4 to match IFLS5 and codebooks
names(IFLS4)[names(IFLS4) == "respndnt"] <- "rspndnt"

```

```{r recode ed}
#recode highest education levels (DL06)

#IFLS4
IFLS4$dl06 <- paste0(IFLS4$dl06)

#check that no new NAs were introduced
for (i in 1:length(IFLS4$dl06)){
IFLS4$dl06_b[i] <-
              if(IFLS4$dl06[i] %in% c("2","11","72")) {2
                  } else if (IFLS4$dl06[i] %in% c("3", "4", "12", "73")) {3
                  } else if (IFLS4$dl06[i] %in% c("5", "6", "15", "74", "14")) {4
                  } else if (IFLS4$dl06[i] %in% c("60", "61", "62", "63", "13")) {5
                  } else if (IFLS4$dl06[i] %in% c("17", "95", "99")) {NA
                  } else if (!(is.na(IFLS4$dl04[i])) & IFLS4$dl04[i] == 3) {1
                  }
else {NA}
}
     

#IFLS5 >>> NOTE: KINDERGARTEN CATEGROIZED AS ELEMENTARY

for (i in 1:length(IFLS5$dl06)){
IFLS5$dl06_b[i] <-  if(str_extract(as.character(IFLS5$dl06[i]), "^[\\d]+(?=:)") %in% c("2","11","72", "90")) {"2:elementary"
                  } else if (str_extract(as.character(IFLS5$dl06[i]), "^[\\d]+(?=:)") %in% c("3", "4", "12", "73")) {"3:juniorH"
                  } else if (str_extract(as.character(IFLS5$dl06[i]), "^[\\d]+(?=:)") %in% c("5", "6", "15", "74", "14")) {"4:seniorH"
                  } else if (str_extract(as.character(IFLS5$dl06[i]), "^[\\d]+(?=:)") %in% c("60", "61", "62", "63", "13")) {"5:higher"
                  } else if (str_extract(as.character(IFLS5$dl06[i]), "^[\\d]+(?=:)") %in% c("17", "95", "98", "99")) {NA
                  } else if (!(is.na(IFLS5$dl04[i])) & IFLS5$dl04[i] == "3:No") {"1:no schooling"
                  }
else {NA}
}

IFLS4$dl06 <- IFLS4$dl06_b
IFLS5$dl06 <- as.factor(IFLS5$dl06_b)

IFLS4$dl06_b <- NULL
IFLS5$dl06_b <- NULL
```

```{r repeat ed recode for husband}


#IFLS4
IFLS4$dl06_H <- paste0(IFLS4$dl06_H)

#check that no new NAs were introduced
for (i in 1:length(IFLS4$dl06_H)){
IFLS4$dl06_H_b[i] <-
              if(IFLS4$dl06_H[i] %in% c("2","11","72")) {2
                  } else if (IFLS4$dl06_H[i] %in% c("3", "4", "12", "73")) {3
                  } else if (IFLS4$dl06_H[i] %in% c("5", "6", "15", "74", "14")) {4
                  } else if (IFLS4$dl06_H[i] %in% c("60", "61", "62", "63", "13")) {5
                  } else if (IFLS4$dl06_H[i] %in% c("17", "95", "99")) {NA
                  } else if (!(is.na(IFLS4$dl04_H[i])) & IFLS4$dl04_H[i] == 3) {1
                  } else {NA
                  }
}
     

#IFLS5 >>> NOTE: KINDERGARTEN CATEGROIZED AS ELEMENTARY

for (i in 1:length(IFLS5$dl06_H)){
IFLS5$dl06_H_b[i] <-  if(str_extract(as.character(IFLS5$dl06_H[i]), "^[\\d]+(?=:)") %in% c("2","11","72", "90")) {"2:elementary"
                  } else if (str_extract(as.character(IFLS5$dl06_H[i]), "^[\\d]+(?=:)") %in% c("3", "4", "12", "73")) {"3:juniorH"
                  } else if (str_extract(as.character(IFLS5$dl06_H[i]), "^[\\d]+(?=:)") %in% c("5", "6", "15", "74", "14")) {"4:seniorH"
                  } else if (str_extract(as.character(IFLS5$dl06_H[i]), "^[\\d]+(?=:)") %in% c("60", "61", "62", "63", "13")) {"5:higher"
                  } else if (str_extract(as.character(IFLS5$dl06_H[i]), "^[\\d]+(?=:)") %in% c("17", "95", "98", "99")) {NA
                  } else if (!(is.na(IFLS5$dl04_H[i])) & IFLS5$dl04_H[i] == "3:No") {"1:no schooling"
                  } else {NA}
}

IFLS4$dl06_H <- IFLS4$dl06_H_b
IFLS5$dl06_H <- as.factor(IFLS5$dl06_H_b)

IFLS4$dl06_H_b <- NULL
IFLS5$dl06_H_b <- NULL

```

```{r list factor vars}

#list of vars for which type == factor in IFLS5
vars <- names(IFLS5)[sapply(IFLS5[,names(IFLS5)], class) == "factor"]

```

```{r releveling function}

relevel_IFLS5 <- function(var){

  lev <- levels(IFLS5[,var])
  num <- as.numeric(str_extract(levels(IFLS5[,var]), "^[\\d]+(?=:)"))
  num <- sort(num)
  lev2 <- vector(length = length(lev))
  for (i in 1:length(lev)){
    lev2[i] <- lev[as.numeric(str_extract(levels(IFLS5[,var]), "^[\\d]+(?=:)")) == num[i]]
  }
  return(lev2)
  
}

```

```{r apply releveling function}

for (i in 1:length(vars)){
levels(IFLS5[,vars[i]]) <-  relevel_IFLS5(vars[i])
}

```

```{r function to convert IFLS4 vectors to labeled factors}

convert <- function(var){
  temp <- as.factor(IFLS4[,var])
  
  #check that all levels are present and the same in both datasets >> could still be issues if coding is inconsistent
  if(length(levels(temp)) == length(levels(IFLS5[,var]))){
    if(sum(levels(temp) == str_extract(levels(IFLS5[,var]), "^[\\d]+(?=:)"))== length(levels(temp))){
  levels(temp) <- levels(IFLS5[,var])}}
  return(temp)
}

```

```{r convert factors}


for (i in 1:length(vars)){
  IFLS4[,vars[i]] <- convert(vars[i])
}


```

```{r check conversion}


level_missing <- c()

#develop a list of vars in which levels don't match across survey years
for (i in 1:length(vars)){
  if(length(levels(IFLS4[,vars[i]])) != length(levels(IFLS5[,vars[i]]))){
    level_missing <- c(level_missing,vars[i])
  }
  else if(sum(levels(IFLS4[,vars[i]]) == levels(IFLS5[,vars[i]])) != length(levels(IFLS4[,vars[i]]))){
    level_missing <- c(level_missing,paste0(vars[i], "**"))
  }
}
 
```


```{r address missing levels}

#borrow missing levels  - tk01

levels(IFLS4$tk01) <- levels(IFLS4$tk01_H)


#another form of converting levels

IFLS4$tk46m_H <- ifelse(is.na(IFLS4$tk46m_H), NA, levels(IFLS5$tk46m_H)[as.numeric(as.character(IFLS4$tk46m_H))])



#covert tk01 and tk46m back to characters to resolve any merge issues (different number of levels)
IFLS4$tk01 <- as.character(IFLS4$tk01)
IFLS5$tk01 <- as.character(IFLS5$tk01)
IFLS4$tk46m_H <- as.character(IFLS4$tk46m_H)
IFLS5$tk46m_H <- as.character(IFLS5$tk46m_H)

```


```{r combine surveys}
issues <- c()

level_mismatch <- c()

#factors with issues
for (i in 1:length(names(IFLS4))){
  if(class(IFLS4[,names(IFLS4)[i]]) == "factor") {
    if(length(levels(IFLS4[,names(IFLS4)[i]])) != length(levels(IFLS5[,names(IFLS4)[i]]))){
      level_mismatch <- c(level_mismatch, names(IFLS4)[i])}
    else if (sum(levels(IFLS4[,names(IFLS4)[i]]) == levels(IFLS5[,names(IFLS4)[i]])) != length(levels(IFLS4[,names(IFLS4)[i]]))){
    issues <- c(issues, names(IFLS4)[i])
  }}
}

#all factors
factors <- c()

for (i in 1:length(names(IFLS4))){

  if (class(IFLS4[,names(IFLS4)[i]])== "factor"){
    
  factors <- c(factors, names(IFLS4)[i])
    
  }
}


#names in need of edits
name_edits_4 <- names(IFLS4)[which(!(names(IFLS4) %in% names(IFLS5)))]
name_edits_5 <- names(IFLS5)[which(!(names(IFLS5) %in% names(IFLS4)))]

#BE VERY CAREFUL HERE! CHECK THIS!!! can produce errors if vars are added
names(IFLS4)[which(!(names(IFLS4) %in% names(IFLS5)))] <- c("pid", "hhid", "hhid_9", "ivwmth", "ivwyr", "hhid_9", "sc_code")
names(IFLS5)[which(!(names(IFLS5) %in% names(IFLS4)))] <- c("pid", "hhid", "hhid_9", "hhid_9", "sc_code")

#identify houses repeated across surveys

repeated <- c()

for (i in 1:length(IFLS4$pidlink)){
  
  if (IFLS4$pidlink[i] %in% IFLS5$pidlink){
    repeated <- c(repeated, IFLS4$pidlink[i])
  }
  
}

#bind
IFLS_4_5 <- bind_rows(IFLS4, IFLS5)

#subset to only include relocated houses
IFLS_4_5 <- IFLS_4_5[which(IFLS_4_5$pidlink %in% repeated),]

```

```{r write to CSV}

write.csv(IFLS_4_5, file = "C:/Users/cheno/Desktop/IFLS_all/DATA/R datasets/IFLS_4_5.csv")

```