---
title: "IFLS5_read_in"
author: "Chenoa Schatzki-McClain and Rosa Zhoe"
date: "March 21, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}

library(foreign)
library(dplyr)


```

```{r load and subset data}

#load B3A_COV IFLS3

B3A_COV_3 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS3/b3a_cov.dta")

#add year variable and filter to selected vars
B3A_COV_3_B <- B3A_COV_3 %>%
                select(pid00, hhid00, pidlink, sex, rspndnt, marstat, panel, age) %>%
                mutate(year = 2013)

#load BK_AR1
BK_AR1_3 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS3/bk_ar1.dta")

#subset
BK_AR1_3_B <- BK_AR1_3 %>%
              select(hhid00, pidlink, ar02b, ar09, ar15a, ar15b)

#load B3A_TK4 >>> lots of missing values
B3A_TK4_3 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS3/b3a_tk4.dta")

#subset
B3A_TK4_3_B <- B3A_TK4_3 %>%
              select(hhid00, pidlink, tk53, tk54, tk55, tk56)

#load B3A_TK1 (employment status)
B3A_TK1_3 <- read.dta("C:/Users/cheno/Desktop/IFLS_all/DATA/IFLS3/b3a_tk1.dta")

#subset
B3A_TK1_3_B <- B3A_TK1_3 %>%
              select(hhid00, pidlink, tk01, tk02, tk03, tk04, tk05, tk07x, tk07, tk08)



```

```{r merge1}

merge1 <- left_join(B3A_COV_3_B, B3A_TK4_3_B, on = c("hhid00", "pidlink"))

missing1 <- merge1[!(merge1$pidlink %in% B3A_TK4_3_B$pidlink),] 

merge2 <- left_join(merge1, B3A_TK1_3_B, on = c("hhid00", "pidlink"))
  
missing2 <- merge2[!(merge2$pidlink %in% B3A_TK1_3_B$pidlink),] 


```