---
title: "Regressions Part 1"
author: "Chenoa Schatzki-McClain"
date: "April 12, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preferred model notes}

### PREFERRED MODELS

#glm5c

#glm6b

```

```{r}
library(dplyr)
library(sampleSelection)
library(ggplot2)
library(plm)
library(tidyr)
```

```{r clear environment}

rm(list=ls())

```

```{r}
#load data
clean <- read.csv("C:/Users/cheno/Desktop/IFLS_all/DATA/R datasets/clean_4_10.csv")

clean$jl_restricted <- ifelse(clean$jl_year %in% 1:2, 1, 0)

clean$employed <- ifelse(as.numeric(clean$employed) == 1, 1, 0)
clean$jl <- ifelse(clean$jl_year == "0", "0", "1")
clean$age_sq <- (clean$age)^2
clean$age_sq_H <- (clean$age_H)^2
clean$jl_year <- as.factor(clean$jl_year)
clean$sc_code <- as.factor(clean$sc_code)
clean$wave <- as.factor(clean$wave)

#wage prof
clean$wage_prof <- ifelse(!(is.na(clean$tk25a1)), clean$tk25a1, ifelse(!(is.na(clean$tk26a1)), clean$tk26a1, NA))

#remove wage outlier >>> optimize this value later on
clean <- clean %>%
              filter(!(!(is.na(wage_prof)) & wage_prof > 10000000))

#remove workers with no hours <<< loook at this later
clean <- clean %>%
              filter(!(!(is.na(clean$tk22a)) & clean$tk22a == 0))

#remove workers with no wage <<< look at the later
clean <- clean %>%
              filter(!(!(is.na(wage_prof)) & wage_prof == 0))

#subset to variables of interest
r1 <- clean %>%
            select(employed, employed_H, jl, age, age_H, age_sq, age_sq_H, dl06, dl06_H, dependents, working_dependents, other_HHM, other_working, sc_code, wave)
```

```{r glm1}

#first regression

glm1a <- glm(employed ~ . , family = binomial, data = r1)
summary(glm1a)

glm1b <- glm(employed ~ . - age_H - age_sq_H, family = binomial, data = r1)
summary(glm1b)

```

```{r}
#subset to variables of interest - use jl_year rather than jl
r2 <- clean %>%
            select(employed, employed_H, jl_year, age, age_H, age_sq, age_sq_H, dl06, dl06_H, dependents, working_dependents, other_HHM, other_working, sc_code, wave)

glm2a <- glm(employed ~ . , family = binomial, data = r2)
summary(glm2a)

glm2b <- glm(employed ~ . - age_H - age_sq_H, family = binomial, data = r2)
summary(glm2b)

```

```{r}
#second regression

#limit job loss to firing/displacement
clean$jl_2 <- ifelse(clean$jl == "1" & as.numeric(clean$tk46m_H) %in% c(1, 2, 5), 1, 0)

#subset to variables of interest
r3 <- clean %>%
            select(employed, employed_H, jl_2, age, age_H, age_sq, age_sq_H, dl06, dl06_H, dependents, working_dependents, other_HHM, other_working, sc_code, wave)

glm3a <- glm(employed ~ . , family = binomial, data = r3)
summary(glm3a)

glm3b <- glm(employed ~ . - age_H - age_sq_H, family = binomial, data = r3)
summary(glm3b)

glm3c <- glm(employed ~ . - age_H - age_sq_H - sc_code, family = binomial, data = r3)
summary(glm3c)

glm3d <- glm(employed ~ . - age_H - age_sq_H - sc_code - wave, family = binomial, data = r3)
summary(glm3d)

```

```{r}

#limit jl_year based on firings
clean$jl_year_fired <- ifelse(clean$jl_year != "0" & !(as.numeric(clean$tk46m_H) %in% c(1, 2, 5)), 0, as.numeric(clean$jl_year)-1)
clean$jl_year_fired <- as.factor(clean$jl_year_fired)

r4 <- clean %>%
            select(employed, employed_H, jl_year_fired, age, age_H, age_sq, age_sq_H, dl06, dl06_H, dependents, working_dependents, other_HHM, other_working, sc_code, wave)

glm4a <- glm(employed ~ . , family = binomial, data = r4)
summary(glm4a)

glm4b <- glm(employed ~ . - age_H - age_sq_H, family = binomial, data = r4)
summary(glm4b)

```

```{r glm5}

#eliminate unpaid family workers from employed

clean$employed2 <- ifelse(clean$employed == 1 & as.numeric(clean$tk24a) == 6, 0, clean$employed)
clean$employed2_H <- ifelse(as.numeric(clean$employed_H) == 1 & as.numeric(clean$tk24a_H) == 6, 0, as.numeric(clean$employed_H))

r5 <- clean %>%
            select(employed2, employed2_H, jl_2, age, age_H, age_sq, age_sq_H, dl06, dl06_H, dependents, working_dependents, other_HHM, other_working, sc_code, wave)

glm5a <- glm(employed2 ~ . , family = binomial, data = r5)
summary(glm5a)

glm5b <- glm(employed2 ~ . - dl06_H, family = binomial, data = r5)
summary(glm5b)

#husband's education is not significant, remove from model
anova(glm5b, glm5a, test = "LRT")

glm5c <- glm(employed2 ~ . - dl06_H -employed2_H, family = binomial, data = r5)
summary(glm5c)

glm5d <- glm(employed2 ~ . - dl06_H -employed2_H - sc_code, family = binomial, data = r5)
summary(glm5d)

#region is significant, keep in model
anova(glm5d, glm5c, test = "LRT")


```

```{r glm6}

#include recoded industry variable

ggplot(clean, aes(x= tk24a, y = tk26a1)) +
      geom_boxplot()+
      ylim(0, 50000000)

ggplot(clean, aes(x= tk24a, y = tk25a1)) +
      geom_boxplot()+
      ylim(0, 50000000)

#new job cat
cats <- c("2:self-employed", "2:self-employed", "3:informal business", "4:government", "5:private", "1:unemployed", "6:casual", "6:casual")

clean$job_cat_H <- c()

for(i in 1:nrow(clean)){
    if(clean$employed_H[i] == 0){
          clean$job_cat_H[i] <- "1:unemployed"
    }
    else {
          clean$job_cat_H[i] <- cats[as.numeric(clean$tk24a_H[i])]
    }
}

clean$job_cat <- c()

for(i in 1:nrow(clean)){
    if(clean$employed[i] == 0){
          clean$job_cat[i] <- "1:unemployed"
    }
    else {
          clean$job_cat[i] <- cats[as.numeric(clean$tk24a[i])]
    }
}

clean$job_cat <- as.factor(clean$job_cat)
clean$job_cat_H <- as.factor(clean$job_cat_H)

r6 <- clean %>%
            select(employed2, job_cat_H, jl_2, age, age_H, age_sq, age_sq_H, dl06, dl06_H, dependents, working_dependents, other_HHM, other_working, sc_code, wave)
                
glm6a <- glm(employed2 ~ . , family = binomial, data = r6)
summary(glm6a)

glm6b <- glm(employed2 ~ . - dl06_H, family = binomial, data = r6)
summary(glm6b)

#husband's education is not significant
anova(glm6b, glm6a, test = "LRT")

glm6c <- glm(employed2 ~ . - dl06_H - sc_code, family = binomial, data = r6)
summary(glm6c)

# region still significant
anova(glm6c, glm6b, test = "LRT")


```

```{r restricted jl var}


#version of glm5c
restricted1 <- clean %>%
            select(employed2, jl_restricted, age, age_H, age_sq, age_sq_H, dl06, dependents, working_dependents, other_HHM, other_working, sc_code, wave)

restricted1a <- glm(employed2 ~ ., family = binomial, data = restricted1)
summary(restricted1a)


#RESTRICTING JL YEARS DOES NOT SUBSTANCIALLY CHANGE THE COEFFICIENT on JL (only p value)
summary(glm5c)



```

```{r}

r7 <- clean %>%
            select(employed2, job_cat_H, jl_year_fired, age, age_H, age_sq, age_sq_H, dl06, dl06_H, dependents, working_dependents, other_HHM, other_working, sc_code, wave)

glm7a <- glm(employed2 ~ . , family = binomial, data = r7)
summary(glm7a)

```

```{r}

#add fixed effects?
clean$pidlink <- as.factor(clean$pidlink)

r8 <- clean %>%
            select(employed2, job_cat_H, jl_2, age, age_H, age_sq, age_sq_H, dl06, dl06_H, dependents, working_dependents, other_HHM, other_working, sc_code, wave, pidlink)

#glm8a <- glm(employed2 ~ . , family = binomial, data = r8)
#summary(glm8a)

#remove NA
r9 <- r8 %>%
      na.omit() %>%
      group_by(pidlink) %>%
      mutate(repeats = n()) %>%
      filter(repeats == 2) %>%
      select(- repeats)


fe1 <- pdata.frame(r8, index=c("pidlink"), drop.index=TRUE, row.names=TRUE)

fe_mod_1 <- plm(formula = employed2 ~ job_cat_H + jl_2 + age + age_H + age_sq + age_sq_H + dl06 + dl06_H + dependents + working_dependents + other_HHM + other_working + sc_code + wave, data = fe1, model = "within")

#removed sc_code, makes sense, as regions is captured by HH fe  
fe_mod_2 <- plm(formula = employed2 ~ job_cat_H + jl_2 + age + age_H + age_sq + age_sq_H + dl06 + dl06_H + dependents + working_dependents + other_HHM + other_working + wave, data = fe1, model = "within")

#removed dl06_H
fe_mod_3 <- plm(formula = employed2 ~ job_cat_H + jl_2 + age + age_H + age_sq + age_sq_H + dl06 + dependents + working_dependents + other_HHM + other_working + wave, data = fe1, model = "within")

summary(fe_mod_1)
summary(fe_mod_2)
summary(fe_mod_3)

#need to test for significance of sc_code, but anova won't work
#anova(fe_mod_2, fe_mod_1, test = "LRT")



```

```{r}

#looking for var the impact participation, but not hours



#create a subset of wives with wage and hours data
workers <- clean %>%
            filter(employed == 1, (!(is.na(tk25a1)) | !(is.na(tk26a1))) & !(is.na(tk22a)))

h1 <- workers %>%
            select(wage_prof, job_cat, job_cat_H, jl_2, age, age_H, age_sq, age_sq_H, dl06, dl06_H, dependents, working_dependents, other_HHM, other_working, sc_code, wave, tk22a)

#first hours regression
hours1a <- glm(tk22a ~ . , data = h1)
summary(hours1a)

hours1b <- glm(tk22a ~ . - job_cat_H -age_H - age_sq_H, data = h1)
summary(hours1b)

```

```{r heckman1}

h1_data <- clean %>% 
                select(employed2, job_cat_H, tk23a2y, jl_2, age, age_H, age_sq, age_sq_H, job_cat, dl06, dependents, working_dependents, other_HHM, other_working, sc_code, wave, wage_prof, tk22a) %>%
                drop_na(- c(wage_prof, tk22a, job_cat, tk23a2y))

p1_data <- h1_data %>%
              select(-c(wage_prof, tk22a, job_cat, tk23a2y))

#probit1 based on glm6b
probit1 <- glm(employed2 ~ . , family = binomial (link = "probit"), data = p1_data)
summary(probit1)

h1_data$mills <- invMillsRatio(probit1)$IMR1

heckit1 <- lm(tk22a ~ . - employed2 - job_cat_H - dependents - other_HHM - other_working + mills, data = h1_data[ h1_data$employed2 == 1, ] )

summary(heckit1)

heckit2 <- lm(tk22a ~ . - employed2 - job_cat_H - dependents - other_HHM - other_working - sc_code + mills, data = h1_data[ h1_data$employed2 == 1, ] )
summary(heckit2)

#region is significant, keep in model
anova(heckit2, heckit1, test = "LRT")

#just employed
h1_employed <- h1_data[ h1_data$employed2 == 1, ] %>%
                  drop_na()


#remove age_H
heckit3 <- lm(tk22a ~ . - employed2 - job_cat_H - dependents - other_HHM - other_working - age_H - age_sq_H + mills, data = h1_employed )
summary(heckit3)

#look at a plot of resid vs. fitted values >> evidence of heteroskedasticity
plot(resid(heckit3)~ h1_employed$wage_prof)
abline(h=0, lty='dashed', col='gray')

#yikes!!
plot(resid(heckit3)~ h1_employed$tk22a)
abline(h=0, lty='dashed', col='gray')

#look at a plot of wage vs. fitted values >> evidence of heteroskedasticity
plot(resid(heckit3)~ fitted.values(heckit3))
abline(h=0, lty='dashed', col='gray')

yikes <- h1_employed[which(fitted.values(heckit3) > 120),]

#try transforming hours

heckit4 <- lm(log(tk22a) ~ . - employed2 - job_cat_H - dependents - other_HHM - other_working - age_H - age_sq_H + mills, data = h1_employed )
summary(heckit4)

#ooof
plot(resid(heckit4)~ h1_employed$tk22a)
abline(h=0, lty='dashed', col='gray')

#not good
plot(resid(heckit4)~ fitted.values(heckit4))
abline(h=0, lty='dashed', col='gray')

#transform wage??
heckit5 <- lm(tk22a ~ . + log(wage_prof) - employed2 - job_cat_H - dependents - other_HHM - other_working - age_H - age_sq_H + mills, data = h1_employed )
summary(heckit5)




```

\newpage

```{r results of interest, tidy = TRUE}
#OVERVIEW of RESULTS

#model with job loss coded as a binomial (could consider narrowing the time period to job loss in past two years)
summary(glm1b)

#model with job loss year
summary(glm2b)

#model with job loss coded as binomial, unpaid family workers reclassified as unemployed
summary(glm5c)

#model with job loss years, unpaid family workers reclassified as unemployed
summary(glm6b)

#model with job loss coded as binomial, unpaid family workers w/ fixed effects
summary(fe_mod_3)

#probit model for heckman
summary(probit1)

#heckman model
summary(heckit3)

```